#region --- AutoIt Macro Generator V 0.21 beta ---
Opt("WinTitleMatchMode", 4)
;  WinWait("classname=ABSxToolShadow","")
;  ControlClick("classname=ABSxToolShadow","","ABSxToolShadow0")
WinWait("SAP2000 v12.0.1 Advanced  - 12_sem_lane","  Moment 3-3 Diagram   (CP-TOT")
WinWait("classname=ABSxToolShadow","")
ControlClick("classname=ABSxToolShadow","","ABSxToolShadow0")
WinWait("classname=ABSxPopup","")
ControlClick("classname=ABSxPopup","","ABSxPopup0")
WinWait("Print Setup","Orientation")
ControlClick("Print Setup","Orientation","ThunderRT6ComboBox3")
ControlClick("Print Setup","Orientation","ThunderRT6Frame4")
ControlClick("Print Setup","Orientation","ThunderRT6CommandButton2")
WinWait("classname=ABSxToolShadow","")
ControlClick("classname=ABSxToolShadow","","ABSxToolShadow0")
WinWait("classname=ABSxPopup","")
ControlClick("classname=ABSxPopup","","ABSxPopup0")
WinWait("Salvar como","&Salvar em:")
ControlClick("Salvar como","&Salvar em:","SysHeader321")
ControlClick("Salvar como","&Salvar em:","Edit1")
ControlClick("Salvar como","&Salvar em:","Button2")
WinWait("Confirmar Salvar como","")
ControlClick("Confirmar Salvar como","","Button1")
WinWait("Program Manager","FolderView")
$CLVItem = ControlListView("Program Manager","FolderView","SysListView321","FindItem","PDF to DWG Converter")
ControlListView("Program Manager","FolderView","SysListView321","SelectClear")
ControlListView("Program Manager","FolderView","SysListView321","Select",$CLVItem)
$CLVItem = ControlListView("Program Manager","FolderView","SysListView321","FindItem","PDF to DWG Converter")
ControlListView("Program Manager","FolderView","SysListView321","SelectClear")
ControlListView("Program Manager","FolderView","SysListView321","Select",$CLVItem)
WinWait("PDF to DWG Converter","Input PDF file")
ControlClick("PDF to DWG Converter","Input PDF file","Button2")
WinWait("Abrir","&Examinar:")
ControlClick("Abrir","&Examinar:","SysHeader321")
$CLVItem = ControlListView("Abrir","&Examinar:","SysListView321","FindItem","Reinaldo")
ControlListView("Abrir","&Examinar:","SysListView321","SelectClear")
ControlListView("Abrir","&Examinar:","SysListView321","Select",$CLVItem)
$CLVItem = ControlListView("Abrir","&Examinar:","SysListView321","FindItem","SAP2000v12.pdf")
ControlListView("Abrir","&Examinar:","SysListView321","SelectClear")
ControlListView("Abrir","&Examinar:","SysListView321","Select",$CLVItem)
ControlClick("Abrir","&Examinar:","Button2")
WinWait("PDF to DWG Converter","Input PDF file")
ControlClick("PDF to DWG Converter","Input PDF file","Button6")
WinWait("AutoDWG PDFIn","View The DWG?")
ControlClick("AutoDWG PDFIn","View The DWG?","Static1")
WinWait("PDF to DWG Converter","Input PDF file")
WinWait("Program Manager","FolderView")
$CLVItem = ControlListView("Program Manager","FolderView","SysListView321","FindItem","SAP2000v12.dwg")
ControlListView("Program Manager","FolderView","SysListView321","SelectClear")
ControlListView("Program Manager","FolderView","SysListView321","Select",$CLVItem)
$CLVItem = ControlListView("Program Manager","FolderView","SysListView321","FindItem","SAP2000v12.dwg")
ControlListView("Program Manager","FolderView","SysListView321","SelectClear")
ControlListView("Program Manager","FolderView","SysListView321","Select",$CLVItem)
#endregion --- End ---
#region --- AutoIt Macro Generator V 0.21 beta ---
Opt("WinTitleMatchMode", 4)
WinWait("SAP2000 v12.0.1 Advanced  - 12_sem_lane","Analysis Model - 3-D View")
ControlClick("SAP2000 v12.0.1 Advanced  - 12_sem_lane","Analysis Model - 3-D View","ThunderRT6PictureBoxDC4")
#endregion --- End ---